# This file was generated by GoReleaser. DO NOT EDIT.
cask "jnh" do
  version "0.17.0"

  on_macos do
    on_intel do
      sha256 "b63f19db5f058c2eb9f74ef63435f660760c60306dc03c2be66da5f82027c67e"
      url "https://storage.googleapis.com/jennah-cli-dist/cli/jnh-v#{version}/jnh-v#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "78f58240ad6cad52e6360d93d7d3812e43005a3a52307c1c3079f8fcd42decb2"
      url "https://storage.googleapis.com/jennah-cli-dist/cli/jnh-v#{version}/jnh-v#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b83132efa155ab7e4c7d2fbc7b35663b8745dce62f74525396d7218511573334"
      url "https://storage.googleapis.com/jennah-cli-dist/cli/jnh-v#{version}/jnh-v#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "2b284d9e49c4980f7a6b23fb01412a177aec0f9b131078deb714610897bd2176"
      url "https://storage.googleapis.com/jennah-cli-dist/cli/jnh-v#{version}/jnh-v#{version}-linux-arm64.tar.gz"
    end
  end

  name "jnh"
  desc "Command-line client for Jennah."
  homepage "https://jennah.nightblue.io/docs/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jnh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jnh"]
    end
  end

  # No zap stanza required

end
