# This file was generated by GoReleaser. DO NOT EDIT.
cask "jnh" do
  version "0.28.0"

  on_macos do
    on_arm do
      sha256 "5b7b748c3ea5fb272c8a64a0da51a254d89df8df2f4b3c479226c75cb3ade6d0"
      url "https://storage.googleapis.com/jennah-cli-dist/cli/jnh-v#{version}/jnh-v#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "a80f5c5170c83d8d2dfdee5f547005c59157da161aa547bb35801169741a6b51"
      url "https://storage.googleapis.com/jennah-cli-dist/cli/jnh-v#{version}/jnh-v#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6ef0a5ef8345141ab47013d036a93c9426b26fa00cdefe7ae1690e9223847d2d"
      url "https://storage.googleapis.com/jennah-cli-dist/cli/jnh-v#{version}/jnh-v#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "81c442eef1f2b1f25639ce365d4cea6204e0256e3413e460a07d6f39b023e944"
      url "https://storage.googleapis.com/jennah-cli-dist/cli/jnh-v#{version}/jnh-v#{version}-linux-amd64.tar.gz"
    end
  end

  name "jnh"
  desc "Command-line client for Jennah."
  homepage "https://jennah.nightblue.io/docs/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jnh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jnh"]
    end
  end

  # No zap stanza required
end
