# This file was generated by GoReleaser. DO NOT EDIT.
cask "jnh" do
  version "0.26.0"

  on_macos do
    on_arm do
      sha256 "885eaf43b416f3f8f6b79e515ffe601c1eb95b44424b3c59fc78f14cba910e09"
      url "https://storage.googleapis.com/jennah-cli-dist/cli/jnh-v#{version}/jnh-v#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "6218e60e72e58909c0347963fc46f02a5685b63df12d7d6364c4c00e00d194af"
      url "https://storage.googleapis.com/jennah-cli-dist/cli/jnh-v#{version}/jnh-v#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "456c7f7d893ed0b0396f41e102fb6173262164805e77f16342032b37fbf8dd48"
      url "https://storage.googleapis.com/jennah-cli-dist/cli/jnh-v#{version}/jnh-v#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "5a573d65a0c6fa0c8efb325ac03720abc5692a8cbf021747d30b1eb1f65cd46b"
      url "https://storage.googleapis.com/jennah-cli-dist/cli/jnh-v#{version}/jnh-v#{version}-linux-amd64.tar.gz"
    end
  end

  name "jnh"
  desc "Command-line client for Jennah."
  homepage "https://jennah.nightblue.io/docs/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jnh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jnh"]
    end
  end

  # No zap stanza required
end
