# This file was generated by GoReleaser. DO NOT EDIT.
class Athena2csv < Formula
  desc "Execute athena query and download csv result."
  homepage "https://github.com/flowerinthenight/athena2csv"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/flowerinthenight/athena2csv/releases/download/v0.1.0/athena2csv_0.1.0_darwin_amd64.tar.gz"
    sha256 "c01a2d9e3505adca297b8e7a50c41f446919f62fcc992a30dcf8ebd4bf5e41b2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/athena2csv/releases/download/v0.1.0/athena2csv_0.1.0_linux_amd64.tar.gz"
      sha256 "ab5eee277803e3a0ddeefad9d446c7ebed05c7bf00f1497ccd5b55fbea82cbee"
    end
  end

  def install
    bin.install "athena2csv"
  end

  test do
    assert_match /Execute athena query and download csv result/, shell_output("#{bin}/athena2csv -h", 0)
  end
end
