# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Athena2csv < Formula
  desc "Execute athena query and download csv result."
  homepage "https://github.com/flowerinthenight/athena2csv"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/athena2csv/releases/download/v0.1.2/athena2csv_0.1.2_darwin_amd64.tar.gz"
      sha256 "56b3356599b12b14f47c3dcfbe04ab61e8d560763d169ba596569cee6299470a"

      def install
        bin.install "athena2csv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/athena2csv/releases/download/v0.1.2/athena2csv_0.1.2_linux_amd64.tar.gz"
      sha256 "a884fd0ba15e951356e4f4e795b049fbf3dccc26826a230e9e0acfd05bb763a3"

      def install
        bin.install "athena2csv"
      end
    end
  end

  test do
    assert_match /Execute athena query and download csv result/, shell_output("#{bin}/athena2csv -h", 0)
  end
end
