# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Athena2csv < Formula
  desc "Execute athena query and download csv result."
  homepage "https://github.com/flowerinthenight/athena2csv"
  version "0.1.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/athena2csv/releases/download/v0.1.1/athena2csv_0.1.1_darwin_amd64.tar.gz"
      sha256 "a0a818e4016e747ce525db145926aa712c99b10e2f9e2ddaab500c63d7407ff6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/athena2csv/releases/download/v0.1.1/athena2csv_0.1.1_linux_amd64.tar.gz"
      sha256 "845fbc87964c27f54de9a0328282cc7f548408853c05f03db1c3f7081de09f76"
    end
  end

  def install
    bin.install "athena2csv"
  end

  test do
    assert_match /Execute athena query and download csv result/, shell_output("#{bin}/athena2csv -h", 0)
  end
end
