# This file was generated by GoReleaser. DO NOT EDIT.
class Dysync < Formula
  desc "Sync DynamoDB table across two AWS accounts."
  homepage "https://github.com/flowerinthenight/dysync"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/flowerinthenight/dysync/releases/download/v1.0.1/dysync_1.0.1_darwin_amd64.tar.gz"
    sha256 "a5d461aa9d71b0670d055c606eb6564472d4cd34c4529abcadc2399c3cbd4e58"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/dysync/releases/download/v1.0.1/dysync_1.0.1_linux_amd64.tar.gz"
      sha256 "8ad8dd42c51cda9c7ebf4cdd8a6718de64ca9fdc2ffd5ffc65291af73c323dae"
    end
  end

  def install
    bin.install "dysync"
  end

  test do
    assert_match /Sync DynamoDB table across two AWS accounts/, shell_output("#{bin}/dysync -h", 0)
  end
end
