# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dysync < Formula
  desc "Sync DynamoDB table across two AWS accounts."
  homepage "https://github.com/flowerinthenight/dysync"
  version "1.1.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/dysync/releases/download/v1.1.1/dysync_1.1.1_darwin_amd64.tar.gz"
      sha256 "71af8ba7323ed0af61ef8c689405b2390e345ee3dc4d3eba6281ab55207f2262"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/dysync/releases/download/v1.1.1/dysync_1.1.1_linux_amd64.tar.gz"
      sha256 "76a720d3b6e3caca7f75abc1e13d7c295db8b17d9ca5b1fd719c3da2c0aead6d"
    end
  end

  def install
    bin.install "dysync"
  end

  test do
    assert_match /Sync DynamoDB table across two AWS accounts/, shell_output("#{bin}/dysync -h", 0)
  end
end
