# This file was generated by GoReleaser. DO NOT EDIT.
class Dysync < Formula
  desc "Sync DynamoDB table across two AWS accounts."
  homepage "https://github.com/flowerinthenight/dysync"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/flowerinthenight/dysync/releases/download/v1.1.0/dysync_1.1.0_darwin_amd64.tar.gz"
    sha256 "b807a0dca8f7e72bc66d360629869a784da6fb292f539c7b5052f8c8097e80ae"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/dysync/releases/download/v1.1.0/dysync_1.1.0_linux_amd64.tar.gz"
      sha256 "cb6f93dd1f3accc1b1cedb4c5632d61668a2b6b9989fb61bd2b22cadbce7a2c8"
    end
  end

  def install
    bin.install "dysync"
  end

  test do
    assert_match /Sync DynamoDB table across two AWS accounts/, shell_output("#{bin}/dysync -h", 0)
  end
end
