# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GSshCmd < Formula
  desc "A simple wrapper to [ssh -t cmd] for AutoScaling Groups."
  homepage "https://github.com/flowerinthenight/g-ssh-cmd"
  version "0.3.11"

  on_macos do
    url "https://github.com/flowerinthenight/g-ssh-cmd/releases/download/v0.3.11/g-ssh-cmd_0.3.11_darwin_amd64.tar.gz"
    sha256 "895bd515618583d4908d0bd30bc623261de60baf797ce35a11dc132fca713087"

    def install
      bin.install "g-ssh-cmd"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the GSshCmd
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/flowerinthenight/g-ssh-cmd/releases/download/v0.3.11/g-ssh-cmd_0.3.11_linux_amd64.tar.gz"
      sha256 "2bcabc871419513a5116a70430e24e6713b57208bef253d05ab01c81d315526d"
      def install
        bin.install "g-ssh-cmd"
      end
    end
  end

  test do
    assert_match /A simple wrapper to/, shell_output("#{bin}/g-ssh-cmd -h", 0)
  end
end
