# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GSshCmd < Formula
  desc "A simple wrapper to [ssh -t cmd] for AutoScaling Groups."
  homepage "https://github.com/flowerinthenight/g-ssh-cmd"
  version "0.3.13"

  on_macos do
    url "https://github.com/flowerinthenight/g-ssh-cmd/releases/download/v0.3.13/g-ssh-cmd_0.3.13_darwin_amd64.tar.gz"
    sha256 "34380bbcb6e313ffd41342b0edcc2bd8a36f7926fc0ec4f7415044153e840ef6"

    define_method(:install) do
      bin.install "g-ssh-cmd"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the GSshCmd
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flowerinthenight/g-ssh-cmd/releases/download/v0.3.13/g-ssh-cmd_0.3.13_linux_amd64.tar.gz"
      sha256 "43584e36d16c69351e7da14a24605df81f6ef0636d05075b84fd278bb232e71d"
      define_method(:install) do
        bin.install "g-ssh-cmd"
      end
    end
  end

  test do
    assert_match /A simple wrapper to/, shell_output("#{bin}/g-ssh-cmd -h", 0)
  end
end
