# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GSshCmd < Formula
  desc "A simple wrapper to [ssh -t cmd] for AutoScaling Groups."
  homepage "https://github.com/flowerinthenight/g-ssh-cmd"
  version "0.3.6"

  on_macos do
    url "https://github.com/flowerinthenight/g-ssh-cmd/releases/download/v0.3.6/g-ssh-cmd_0.3.6_darwin_amd64.tar.gz"
    sha256 "ee01b2dccb88a2499012184f43d2cca027caa621a4ca70e4a6cbc12233d9cab6"

    def install
      bin.install "g-ssh-cmd"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the GSshCmd
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flowerinthenight/g-ssh-cmd/releases/download/v0.3.6/g-ssh-cmd_0.3.6_linux_amd64.tar.gz"
        sha256 "462580546541adb0d9225924f81f1031cc19507d01823efc1db4907bfa9df85a"

        def install
          bin.install "g-ssh-cmd"
        end
      end
    end
  end

  test do
    assert_match /A simple wrapper to/, shell_output("#{bin}/g-ssh-cmd -h", 0)
  end
end
