# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hedged < Formula
  desc "A generic daemon based on https://flowerinthenight/hedge/."
  homepage "https://github.com/flowerinthenight/hedged"
  version "0.2.0"

  on_macos do
    url "https://github.com/flowerinthenight/hedged/releases/download/v0.2.0/hedged_0.2.0_darwin_amd64.tar.gz"
    sha256 "ee85fac2990a3755f2556067e093794b73521b6fe4c65c569393d43e1f3cb009"

    def install
      bin.install "hedged"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Hedged
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flowerinthenight/hedged/releases/download/v0.2.0/hedged_0.2.0_linux_amd64.tar.gz"
        sha256 "106e505595ec57a36e46ecc0b4f2b8808e646204dfa4bf648099f767f19a1bcb"

        def install
          bin.install "hedged"
        end
      end
    end
  end

  test do
    assert_match /A generic daemon based on https, shell_output("#{bin}/hedged -h", 0)
  end
end
