# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hedged < Formula
  desc "A generic daemon based on https://flowerinthenight/hedge/."
  homepage "https://github.com/flowerinthenight/hedged"
  version "0.1.1"

  on_macos do
    url "https://github.com/flowerinthenight/hedged/releases/download/v0.1.1/hedged_0.1.1_darwin_amd64.tar.gz"
    sha256 "23b6c2562860033636358be316242e4a19d0d6a7dd3f794570b3daebd29e43cb"

    def install
      bin.install "hedged"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Hedged
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flowerinthenight/hedged/releases/download/v0.1.1/hedged_0.1.1_linux_amd64.tar.gz"
        sha256 "42be787f0a6ab651f8aea9ef57f471fd9169b8ecab14dc73971a47be69c8af21"

        def install
          bin.install "hedged"
        end
      end
    end
  end

  test do
    assert_match /A generic daemon based on https, shell_output("#{bin}/hedged -h", 0)
  end
end
