# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hedged < Formula
  desc "Generic cluster service built on hedge."
  homepage "https://github.com/flowerinthenight/hedged"
  version "0.3.0"
  depends_on :linux

  if Hardware::CPU.intel?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/flowerinthenight/hedged/releases/download/v0.3.0/hedged_0.3.0_linux_amd64.tar.gz"
      sha256 "be06cf5cd805e584b29a42992a5a1a2448793b98ff6e744d9f56c1ee2aa6022c"

      def install
        bin.install "hedged"
      end
    end
  end

  test do
    assert_match /Generic cluster service built on hedge/, shell_output("#{bin}/freyr -h", 0)
  end
end
