# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubepfm < Formula
  desc "A simple port-forward wrapper tool for multiple pods/deployments/services."
  homepage "https://github.com/flowerinthenight/kubepfm"
  version "1.6.4"

  on_macos do
    url "https://github.com/flowerinthenight/kubepfm/releases/download/v1.6.4/kubepfm_1.6.4_darwin_amd64.tar.gz"
    sha256 "e643726b68f8533e10d7907a23ab70563f0f71dcd5a317ef26ec2c9e2cc228e6"

    def install
      bin.install "kubepfm"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kubepfm
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/kubepfm/releases/download/v1.6.4/kubepfm_1.6.4_linux_amd64.tar.gz"
      sha256 "6ec0fea2aa7b257934b5fc37145f7ee63d33c5e2d1d1f2183bc6798434640383"

      def install
        bin.install "kubepfm"
      end
    end
  end

  test do
    assert_match /A simple port-forward wrapper tool for multiple pods\/deployments\/services/, shell_output("#{bin}/kubepfm -h", 0)
  end
end
