# This file was generated by GoReleaser. DO NOT EDIT.
class Kubepfm < Formula
  desc "Simple port-forward wrapper tool for multiple pods."
  homepage "https://github.com/flowerinthenight/kubepfm"
  version "1.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/flowerinthenight/kubepfm/releases/download/v1.4.0/kubepfm_1.4.0_darwin_amd64.tar.gz"
    sha256 "11f4177286d41dd976bac854c244a8498abd5912394550f9e1896620fc82a28a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/kubepfm/releases/download/v1.4.0/kubepfm_1.4.0_linux_amd64.tar.gz"
      sha256 "8367406f6bd3a588ec6ad75b76cb3bce14b92adde35cce20c398101239f65593"
    end
  end

  def install
    bin.install "kubepfm"
  end

  test do
    assert_match /Simple port-forward wrapper tool for multiple pods/, shell_output("#{bin}/kubepfm -h", 0)
  end
end
