# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubepfm < Formula
  desc "A simple port-forward wrapper tool for multiple pods/deployments/services."
  homepage "https://github.com/flowerinthenight/kubepfm"
  version "1.6.5"

  on_macos do
    url "https://github.com/flowerinthenight/kubepfm/releases/download/v1.6.5/kubepfm_1.6.5_darwin_amd64.tar.gz"
    sha256 "6597113baecd8a3d54175c8716af18f879f0d6f7eda61926f66a36b7bca49364"

    def install
      bin.install "kubepfm"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kubepfm
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/kubepfm/releases/download/v1.6.5/kubepfm_1.6.5_linux_amd64.tar.gz"
      sha256 "898dac7a3028efd1708f040324f32f4f69652b71699ee9d05f7aeef7743cdb16"

      def install
        bin.install "kubepfm"
      end
    end
  end

  test do
    assert_match /A simple port-forward wrapper tool for multiple pods\/deployments\/services/, shell_output("#{bin}/kubepfm -h", 0)
  end
end
