# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lsdy < Formula
  desc "DynamoDB query tool."
  homepage "https://github.com/flowerinthenight/lsdy"
  version "1.8.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/lsdy/releases/download/v1.8.6/lsdy_1.8.6_darwin_amd64.tar.gz"
      sha256 "d4c6dd8e3f2d66437404d12ae5b7e4ad7cd63c2e2792a7448fedb1b0c9a43e32"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/lsdy/releases/download/v1.8.6/lsdy_1.8.6_linux_amd64.tar.gz"
      sha256 "2fb1befb23b2384f52070f41816fe25dcc1c7ed7130b183fedd024a918dc45d5"
    end
  end

  def install
    bin.install "lsdy"
  end

  test do
    assert_match /DynamoDB query tool/, shell_output("#{bin}/lsdy -h", 0)
  end
end
