# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lunactl < Formula
  desc "Test cmdline for luna."
  homepage "https://github.com/flowerinthenight/lunactl"
  version "0.2.0"

  on_macos do
    url "https://github.com/flowerinthenight/lunactl/releases/download/v0.2.0/lunactl_0.2.0_darwin_amd64.tar.gz"
    sha256 "97dc22e0adfe8ab7e51d41531bc0c1526474bb013f44a588534310cb0684b346"

    def install
      bin.install "lunactl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Lunactl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flowerinthenight/lunactl/releases/download/v0.2.0/lunactl_0.2.0_linux_amd64.tar.gz"
      sha256 "663520336b656613498faa2afacb94d940b7f2a3bfe276a3ba78930e7d08d0ed"
      def install
        bin.install "lunactl"
      end
    end
  end

  test do
    assert_match /Usage of/, shell_output("#{bin}/lunactl -h", 0)
  end
end
