# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lunactl < Formula
  desc "Test cmdline for luna."
  homepage "https://github.com/flowerinthenight/lunactl"
  version "0.3.2"

  on_macos do
    url "https://github.com/flowerinthenight/lunactl/releases/download/v0.3.2/lunactl_0.3.2_darwin_amd64.tar.gz"
    sha256 "33ba7e55c9185c1fd1d45ffd37c3564dafad6307aa8f38497e2b0a597b411882"

    def install
      bin.install "lunactl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Lunactl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flowerinthenight/lunactl/releases/download/v0.3.2/lunactl_0.3.2_linux_amd64.tar.gz"
      sha256 "9c35bf0f0d4a44f6b12cd7c4b675d4fc0a7712f0b7dcd6a19fc895127e64559f"
      def install
        bin.install "lunactl"
      end
    end
  end

  test do
    assert_match /Usage of/, shell_output("#{bin}/lunactl -h", 0)
  end
end
