# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lunactl < Formula
  desc "Test cmdline for luna."
  homepage "https://github.com/flowerinthenight/lunactl"
  version "0.1.0"

  on_macos do
    url "https://github.com/flowerinthenight/lunactl/releases/download/v0.1.0/lunactl_0.1.0_darwin_amd64.tar.gz"
    sha256 "d25493e149465a31b6603b61bf27d997c7aee0a279139fd28c9aaf2d4a46fc76"

    def install
      bin.install "lunactl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Lunactl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flowerinthenight/lunactl/releases/download/v0.1.0/lunactl_0.1.0_linux_amd64.tar.gz"
      sha256 "06b14e16622eebe5f03e998f9c067048bcb9eda650cfeb9e87d1b3ed5dc6a90f"
      def install
        bin.install "lunactl"
      end
    end
  end

  test do
    assert_match /Usage of/, shell_output("#{bin}/lunactl -h", 0)
  end
end
