# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OomkillWatch < Formula
  desc "A simple kubectl wrapper tool for tailing OOMKilling events."
  homepage "https://github.com/flowerinthenight/oomkill-watch"
  version "0.3.2"

  on_macos do
    url "https://github.com/flowerinthenight/oomkill-watch/releases/download/v0.3.2/oomkill-watch_0.3.2_darwin_amd64.tar.gz"
    sha256 "97b5be5ff3fbd8327b5414798a2be0d2bcd48cd35e223b1904cec9da8b60da62"

    define_method(:install) do
      bin.install "oomkill-watch"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the OomkillWatch
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flowerinthenight/oomkill-watch/releases/download/v0.3.2/oomkill-watch_0.3.2_linux_amd64.tar.gz"
      sha256 "251f23fd02accb59c9035f671c3849187b5c98838d530201e1385cdd97cac968"
      define_method(:install) do
        bin.install "oomkill-watch"
      end
    end
  end

  test do
    assert_match /Usage of/, shell_output("#{bin}/oomkill-watch -h", 0)
  end
end
