# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OomkillWatch < Formula
  desc "A simple kubectl wrapper tool for tailing OOMKilling events."
  homepage "https://github.com/flowerinthenight/oomkill-watch"
  version "0.3.3"

  on_macos do
    url "https://github.com/flowerinthenight/oomkill-watch/releases/download/v0.3.3/oomkill-watch_0.3.3_darwin_amd64.tar.gz"
    sha256 "80f91abe809a9662228b6ce79316866ed6048466c25c97aaba8cbe193cf4bb12"

    define_method(:install) do
      bin.install "oomkill-watch"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the OomkillWatch
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flowerinthenight/oomkill-watch/releases/download/v0.3.3/oomkill-watch_0.3.3_linux_amd64.tar.gz"
      sha256 "f64a5b1a426762bd4f6592fc45cc859bf2ed20d43450e29c6c85907bd0b8a0b4"
      define_method(:install) do
        bin.install "oomkill-watch"
      end
    end
  end

  test do
    assert_match /Usage of/, shell_output("#{bin}/oomkill-watch -h", 0)
  end
end
