# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OomkillWatch < Formula
  desc "A simple kubectl wrapper tool for tailing OOMKilling events."
  homepage "https://github.com/flowerinthenight/oomkill-watch"
  version "0.3.1"

  on_macos do
    url "https://github.com/flowerinthenight/oomkill-watch/releases/download/v0.3.1/oomkill-watch_0.3.1_darwin_amd64.tar.gz"
    sha256 "d2f6bfce1cdfc06e29bfd4ae9314b549d87ecde621284dbb155c7f34b53338a0"

    def install
      bin.install "oomkill-watch"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the OomkillWatch
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/oomkill-watch/releases/download/v0.3.1/oomkill-watch_0.3.1_linux_amd64.tar.gz"
      sha256 "355a956e319ea9ab4cbdb35658921dd15227938ee1f388fe3a3a41f9164c278c"

      def install
        bin.install "oomkill-watch"
      end
    end
  end

  test do
    assert_match /Usage of/, shell_output("#{bin}/oomkill-watch -h", 0)
  end
end
