# This file was generated by GoReleaser. DO NOT EDIT.
class Oops < Formula
  desc "Kubernetes-native testing tool."
  homepage "https://github.com/flowerinthenight/oops"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/flowerinthenight/oops/releases/download/v0.5.0/oops_0.5.0_darwin_amd64.tar.gz"
    sha256 "fde61f7d00c99c501079a0a7588c7228a161f88e70db916b3a2382103a461c06"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/oops/releases/download/v0.5.0/oops_0.5.0_linux_amd64.tar.gz"
      sha256 "160a53cdccaa0db5a6d845a50984c81b7318d0399de0fab1af5f3ac1679ced4b"
    end
  end

  def install
    bin.install "oops"
  end

  test do
    assert_match /Kubernetes-native testing tool/, shell_output("#{bin}/oops -h", 0)
  end
end
