# This file was generated by GoReleaser. DO NOT EDIT.
class Oops < Formula
  desc "Kubernetes-native testing tool."
  homepage "https://github.com/flowerinthenight/oops"
  version "0.2.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/flowerinthenight/oops/releases/download/v0.2.5/oops_0.2.5_darwin_amd64.tar.gz"
    sha256 "f7c404e4a8ba9597cb30ed714bf5a6742465fe69a5064f08a12f52ce26306c47"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/flowerinthenight/oops/releases/download/v0.2.5/oops_0.2.5_linux_amd64.tar.gz"
      sha256 "7a38e6ef1810b7c76084047b5ab141be55a231a675da9b7650314c3d8012c492"
    end
  end

  def install
    bin.install "oops"
  end

  test do
    assert_match /Kubernetes-native testing tool/, shell_output("#{bin}/oops -h", 0)
  end
end
